name: Build and Release NinjaMagisk Windows Tools

on:
  push:
    tags:
      - 'v*.*.*' # Triggers only when you push a tag like v1.0.0

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Adjust this to your project's .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore "NinjaMagisk Windows Tools.sln"

      # Build the solution (Release configuration)
      - name: Build Release
        run: dotnet build "NinjaMagisk Windows Tools.sln" --configuration Release --no-restore

      # Package the output into a zip
      - name: Package Release
        run: |
          cd "NinjaMagisk Windows Tools/bin/Release"
          powershell -Command "Compress-Archive -Path * -DestinationPath ../../../NinjaMagisk-Windows-Tools-Release.zip"

      # Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Upload the zip to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: NinjaMagisk-Windows-Tools-Release.zip
          asset_name: NinjaMagisk-Windows-Tools-${{ github.ref_name }}.zip
          asset_content_type: application/zip
